const hotels = [
  {
    id: 1,
    name: "Equitana Hotel Resort",
    activities: [
      "outdoors",
      "sport",
      "kids",
      "horse-riding",
      "spa",
      "relax",
      "bowling",
      "billiard",
      "minigolf",
      "fishing",
    ],
    "loc-code": "cs-c",
    address: "Martinice 1, 262 72 Březnice, Czech Republic",
    location: {
      latitude: 49.5791,
      longitude: 13.8301,
    },
    rating: 4,
    price: "midrange",
    comfort: ["wifi", "parking", "pool", "restaurant", "jogging-track"],
    web: "http://www.equitana.cz",
    images: ["/assets/Equitana/horse-kid.jpg"],
  },
  {
    id: 2,
    name: "Hotel Kouty",
    activities: [
      "outdoors",
      "sport",
      "tennis",
      "beach-volleyball",
      "paddleboard",
      "yoga",
      "relax",
      "playground",
    ],
    "loc-code": "cs-c",
    address: "Zblovice 63, 675 26 Zblovice, Czech Republic",
    location: {
      latitude: 49.106,
      longitude: 15.645,
    },
    rating: 4,
    price: "midrange",
    comfort: ["wifi", "parking", "sauna", "restaurant"],
    web: "http://www.hotelkouty.cz",
    images: [],
  },
  {
    id: 3,
    name: "Golf Resort Olomouc",
    activities: ["outdoors", "golf"],
    "loc-code": "cs-c",
    address: "Dolany-Véska 89, 783 16 Dolany, Czech Republic",
    location: {
      latitude: 49.635,
      longitude: 17.3023,
    },
    rating: 4,
    price: "midrange",
    comfort: ["wifi", "parking", "pets", "restaurant", "gym", "club rentals"],
    web: "https://www.golfolomouc.cz/en/hotel/hotel",
    images: [],
  },
  {
    id: 4,
    name: "Caribe Bay",
    activities: ["kids", "aquapark", "playground"],
    "loc-code": "it-c",
    address:
      "Via Michelangelo Buonarroti, 15, 30016 Lido di Jesolo, Venice, Italy",
    location: {
      latitude: 45.5128,
      longitude: 12.6446,
    },
    rating: 4,
    price: "midrange",
    comfort: ["pool", "restaurant", "wifi"],
    web: "https://www.caribebay.it/en",
    images: [],
  },
  {
    id: 5,
    name: "Six Senses Douro Valley",
    activities: [
      "art",
      "painting",
      "sport",
      "water-sports",
      "cooking-masterclass",
      "wine-tasting",
    ],
    "loc-code": "pt-c",
    address: "Quinta Vale de Abraão, Samodães, 5100-758 Lamego, Portugal",
    location: {
      latitude: 41.161,
      longitude: -7.7851,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "restaurant", "pool", "wine cellar"],
    web: "https://www.sixsenses.com/en/resorts/douro-valley/experiences/",
    images: [],
  },
  {
    id: 6,
    name: "The Boulders Resort",
    activities: [
      "golf",
      "hotair-balloons",
      "rock-climbing",
      "outdoors",
      "sport",
    ],
    "loc-code": "us-c",
    address: "34631 N Tom Darlington Dr, Scottsdale, AZ 85262, USA",
    location: {
      latitude: 33.8466,
      longitude: -111.9277,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "gym", "restaurant"],
    web: "https://www.theboulders.com/outdoor-adventures/",
    images: [],
  },
  {
    id: 7,
    name: "The Residences at Chevy Chase",
    activities: ["pillow fighting", "relax"],
    "loc-code": "us-c",
    address: "8551 Connecticut Ave, Chevy Chase, MD 20815, USA",
    location: {
      latitude: 38.9965,
      longitude: -77.069,
    },
    rating: 0,
    price: "luxury",
    comfort: ["gym", "library", "pet"],
    web: "https://www.theresidenceschevychase.com/",
    images: [],
  },
  {
    id: 8,
    name: "Loews Coronado Bay Resort",
    activities: ["surfing for dogs", "outdoors", "sport"],
    "loc-code": "us-c",
    address: "4000 Coronado Bay Road, Coronado, CA 92118, USA",
    location: {
      latitude: 32.6325,
      longitude: -117.1384,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "parking", "pool", "restaurant"],
    web: "https://www.loewshotels.com/coronado-bay-resort",
    images: [],
  },
  {
    id: 9,
    name: "Obriy Village",
    activities: [
      "traditional Ukrainian hot tubs",
      "horse-riding",
      "relax",
      "outdoors",
      "sport",
    ],
    "loc-code": "ua-c",
    address: "Opishnya, Poltava region, Ukraine",
    location: {
      latitude: 49.9722,
      longitude: 34.6083,
    },
    rating: 4.5,
    price: "budget",
    comfort: ["wifi", "parking", "restaurant", "spa"],
    web: "https://obriyvillage.com/",
    images: [],
  },
  {
    id: 10,
    name: "Concept Stay Sirimiri",
    activities: ["horse-riding", "hot tubs", "relax", "outdoors", "sport"],
    "loc-code": "ua-c",
    address: "Yaremche, Ukraine",
    location: {
      latitude: 48.4482,
      longitude: 24.5527,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "parking", "restaurant", "spa"],
    web: "https://en.concept-stay.com/sirimiri",
    images: [],
  },
  {
    id: 11,
    name: "Scandi Eco Park",
    activities: [
      "kids",
      "playground",
      "sport",
      "outdoors",
      "pet therapy",
      "husky dogs",
      "horse-riding",
      "cycling",
      "trekking",
    ],
    "loc-code": "ua-c",
    address: "Chernihiv, Ukraine",
    location: {
      latitude: 51.4982,
      longitude: 31.2893,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "parking", "restaurant", "spa"],
    web: "https://www.facebook.com/scandi.eco.park/",
    images: [],
  },
  {
    id: 12,
    name: "Aves Travel",
    activities: ["hot springs", "relax"],
    "loc-code": "ua-c",
    address: "Various locations, Ukraine",
    location: {
      latitude: 48.3794,
      longitude: 31.1656,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "parking", "restaurant", "spa"],
    web: "https://www.avestravel.com.ua/hotel_list/goteli-z-garjachimi-dzherelami-v-ukraini/",
    images: [],
  },
  {
    id: 13,
    name: "The Manta Resort",
    activities: ["underwater hotel", "outdoors", "relax"],
    "loc-code": "tz-c",
    address: "Pemba Island, Tanzania",
    location: {
      latitude: -5.235,
      longitude: 39.7763,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "parking", "restaurant", "spa"],
    web: "https://themantaresort.com/",
    images: [],
  },
  {
    id: 14,
    name: "Poseidon Undersea Resorts",
    activities: ["underwater hotel", "relax"],
    "loc-code": "fj-c",
    address: "Fiji Island",
    location: {
      latitude: -17.7134,
      longitude: 178.065,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "restaurant", "spa"],
    web: "https://www.poseidonresorts.com/",
    images: [],
  },
  {
    id: 15,
    name: "Icehotel",
    activities: ["ice hotel", "art"],
    "loc-code": "se-c",
    address: "Marknadsvägen 63, 981 91 Jukkasjärvi, Sweden",
    location: {
      latitude: 67.85,
      longitude: 20.6161,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "restaurant", "bar"],
    web: "https://www.icehotel.com/",
    images: [],
  },
  {
    id: 16,
    name: "Treehotel",
    activities: ["outdoors", "relax"],
    "loc-code": "se-c",
    address: "Edeforsväg 2A, 960 24 Harads, Sweden",
    location: {
      latitude: 65.8254,
      longitude: 20.9694,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "restaurant", "sauna"],
    web: "https://treehotel.se/",
    images: [],
  },
  {
    id: 17,
    name: "Luna Salada Hotel",
    activities: ["salt hotel", "relax"],
    "loc-code": "bo-c",
    address: "Salar de Uyuni, Colchani, Bolivia",
    location: {
      latitude: -20.1338,
      longitude: -67.4891,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "restaurant", "spa"],
    web: "https://lunasaladahotel.com.bo/",
    images: [],
  },
  {
    id: 18,
    name: "Happy Guests Lodge",
    activities: ["fish companion for £5", "relax"],
    "loc-code": "gb-c",
    address: "Tarporley Road, Dutton, Warrington WA4 4EZ, England",
    location: {
      latitude: 53.3,
      longitude: -2.65,
    },
    rating: 4,
    price: "budget",
    comfort: ["wifi", "parking", "restaurant", "pets"],
    web: "http://www.happyguestslodge.co.uk/",
    images: [],
  },
  {
    id: 19,
    name: "Hotel Divorce",
    activities: ["divorce hotel", "relax"],
    "loc-code": "nl-c",
    address: "Zeestraat 35, 2518 AA The Hague, Netherlands",
    location: {
      latitude: 52.0833,
      longitude: 4.3,
    },
    rating: 4,
    price: "midrange",
    comfort: ["wifi", "restaurant", "spa", "legal services"],
    web: "https://www.carlton.nl/hotel-ambassador-den-haag",
    images: [],
  },
  {
    id: 20,
    name: "Protea Hotel by Marriott Polokwane Ranch Resort",
    activities: ["walk with lions", "outdoors"],
    "loc-code": "za-c",
    address:
      "25 km South of Polokwane on either the R101 or N1, Polokwane, 0700, South Africa",
    location: {
      latitude: -23.8916,
      longitude: 29.4486,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["wifi", "restaurant", "spa", "pool"],
    web: "https://www.marriott.com/en-us/hotels/ptgra-protea-hotel-polokwane-ranch-resort/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0",
    images: [],
  },
  {
    id: 21,
    name: "V8 Hotel Classic Motorworld Region Stuttgart",
    activities: ["relax", "art"],
    "loc-code": "de-c",
    address: "Charles-Lindbergh-Platz 1, 71034 Böblingen, Germany",
    location: {
      latitude: 48.681,
      longitude: 8.9999,
    },
    rating: 4.5,
    price: "midrange",
    comfort: ["restaurant", "bar", "gym"],
    web: "https://www.v8hotel.de/",
    images: [],
  },
  {
    id: 22,
    name: "Masseria Cervarolo",
    activities: ["art", "outdoors", "relax"],
    "loc-code": "it-c",
    address: "SP 14 Ostuni-Martina Franca, km 4,5, 72017 Ostuni BR, Italy",
    location: {
      latitude: 40.7392,
      longitude: 17.5816,
    },
    rating: 4.8,
    price: "midrange",
    comfort: ["spa", "pool", "restaurant", "garden"],
    web: "https://www.booking.com",
    images: [],
  },
  {
    id: 23,
    name: "Electra Palace Hotel",
    activities: ["art", "outdoors", "relax"],
    "loc-code": "gr-c",
    address: "9 Aristotelous Square, Thessaloniki, 546 24, Greece",
    location: {
      latitude: 40.6323,
      longitude: 22.9404,
    },
    rating: 4.7,
    price: "midrange",
    comfort: ["pool", "restaurant"],
    web: "https://www.booking.com",
    images: [],
  },
  {
    id: 24,
    name: "Gaylord Palms and Convention Center",
    activities: [
      "kids",
      "sport",
      "outdoors",
      "playground",
      "ice-skating",
      "surfing",
    ],
    address: "6000 W Osceola Pkwy, Kissimmee, FL 34746, USA",
    location: {
      latitude: 28.3514,
      longitude: -81.5331,
    },
    rating: 4.6,
    price: "midrange",
    comfort: ["spa", "restaurant", "pool"],
    web: "https://www.marriott.com/en-us/hotels/mcogp-gaylord-palms-resort-and-convention-center/overview/",
    images: [],
  },
  {
    id: 25,
    name: "Treebones Resort",
    activities: [
      "glamping in yurts",
      "private decks with scenic views",
      "outdoors",
      "art",
      "relax",
      "hiking",
    ],
    "loc-code": "us-c",
    address: "71895 CA-1, Big Sur, CA 93920, USA",
    location: {
      latitude: 35.9643,
      longitude: -121.537,
    },
    rating: 4.5,
    price: "budget",
    comfort: ["restaurant", "pets", "Organic garden", "Hiking trails"],
    web: "https://www.treebonesresort.com/",
    images: [],
  },
  {
    id: 26,
    name: "Hotel Max",
    activities: ["art"],
    "loc-code": "us-c",
    address: "620 Stewart St, Seattle, WA 98101, USA",
    location: {
      latitude: 47.6132,
      longitude: -122.3361,
    },
    rating: 4.4,
    price: "midrange",
    comfort: ["restaurant", "gym"],
    web: "https://www.creativetravelguide.com",
    images: [],
  },
  {
    id: 27,
    name: "Grand Velas Riviera Maya",
    activities: ["art", "sport"],
    "loc-code": "mx-c",
    address:
      "Carretera Cancún Tulum Km 62, 77710 Playa del Carmen, Q.R., Mexico",
    location: {
      latitude: 20.6371,
      longitude: -87.0568,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["spa", "pool", "restaurant"],
    web: "https://www.grandvelas.com",
    images: [],
  },
  {
    id: 28,
    name: "W Barcelona",
    activities: ["yoga", "relax", "salsa nights"],
    "loc-code": "es-c",
    address: "Plaça de la Rosa dels Vents, 1, 08039 Barcelona, Spain",
    location: {
      latitude: 41.3684,
      longitude: 2.1924,
    },
    rating: 4.7,
    price: "midrange",
    comfort: ["beach", "pool", "restaurant"],
    web: "https://www.marriott.com",
    images: [],
  },
  {
    id: 29,
    name: "Hotel del Coronado",
    activities: ["yoga", "sport", "outdoors"],
    "loc-code": "us-c",
    address: "1500 Orange Ave, Coronado, CA 92118, USA",
    location: {
      latitude: 32.6809,
      longitude: -117.1784,
    },
    rating: 4.6,
    price: "luxury",
    comfort: ["restaurant", "spa", "beach"],
    web: "https://hoteldel.com/",
    images: [],
  },
  {
    id: 30,
    name: "Amangiri",
    activities: [
      "outdoors",
      "sport",
      "relax",
      "stargazing",
      "hot-air-ballooning",
      "hiking",
      "horse-riding",
    ],
    "loc-code": "us-c",
    address: "1 Kayenta Rd, Canyon Point, UT 84741, USA",
    location: {
      latitude: 37.0185,
      longitude: -111.9291,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["spa", "pool", "restaurant"],
    web: "https://www.aman.com/resorts/amangiri",
    images: [],
  },
  {
    id: 31,
    name: "Soneva Fushi",
    activities: [
      "snorkeling",
      "outdoors",
      "diving",
      "art",
      "private cinema screenings",
      "chocolate-making classes",
    ],
    "loc-code": "mv-c",
    address: "Kunfunadhoo Island, Baa Atoll, Maldives",
    location: {
      latitude: 5.7264,
      longitude: 73.003,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["spa", "restaurant", "beach"],
    web: "https://www.soneva.com/soneva-fushi/",
    images: [],
  },
  {
    id: 32,
    name: "Fogo Island Inn",
    activities: [
      "iceberg watching",
      "boat tours",
      "artist-in-residence programs",
      "berry picking",
      "art",
      "outdoors",
    ],
    "loc-code": "ca-c",
    address: "210 Main Rd, Joe Batt's Arm, NL A0G 2X0, Canada",
    location: {
      latitude: 49.7174,
      longitude: -54.176,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["restaurant", "spa", "library"],
    web: "https://www.fogoislandinn.ca/",
    images: [],
  },
  {
    id: 33,
    name: "Kakslauttanen Arctic Resort",
    activities: [
      "aurora hunting",
      "outdoors",
      "husky sledding",
      "fishing",
      "kids",
      "playground",
    ],
    "loc-code": "fi-c",
    address: "Kiilopääntie 9, 99830 Saariselkä, Finland",
    location: {
      latitude: 68.4186,
      longitude: 27.4177,
    },
    rating: 4.7,
    price: "midrange",
    comfort: ["spa", "restaurant"],
    web: "https://www.kakslauttanen.fi/",
    images: [],
  },
  {
    id: 34,
    name: "Whitepod Eco-Luxury Hotel",
    activities: [
      "skiing",
      "sport",
      "outdoors",
      "snowshoeing",
      "yoga",
      "stargazing",
    ],
    "loc-code": "ch-c",
    address: "Les Giettes, 1871 Monthey, Switzerland",
    location: {
      latitude: 46.2176,
      longitude: 6.9144,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa"],
    web: "https://www.whitepod.com/",
    images: [],
  },
  {
    id: 35,
    name: "Amilla Fushi",
    activities: [
      "outdoors",
      "submarine tours",
      "private island picnics",
      "fishing",
      "underwater dining",
    ],
    "loc-code": "mv-c",
    address: "Baa Atoll, Maldives",
    location: {
      latitude: 5.7832,
      longitude: 73.4023,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["spa", "restaurant", "beach"],
    web: "https://www.amilla.com/",
    images: [],
  },
  {
    id: 36,
    name: "Longitude 131°",
    activities: [
      "uluru sunrise tours",
      "camel treks",
      "indigenous cultural experiences",
      "art",
      "outdoors",
    ],
    "loc-code": "au-c",
    address: "Yulara Drive, Yulara NT 0872, Australia",
    location: {
      latitude: -25.3447,
      longitude: 131.0369,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa", "pool"],
    web: "https://longitude131.com.au/",
    images: [],
  },
  {
    id: 37,
    name: "Soneva Kiri",
    activities: [
      "treepod dining",
      "private beach dinners",
      "snorkeling",
      "stargazing",
      "relax",
      "outdoors",
    ],
    "loc-code": "th-c",
    address: "110 Moo 4, Ko Kut, Trat 23000, Thailand",
    location: {
      latitude: 11.589,
      longitude: 102.526,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["spa", "pool"],
    web: "https://www.soneva.com/soneva-kiri/",
    images: [],
  },
  {
    id: 38,
    name: "The Singular Patagonia",
    activities: [
      "outdoors",
      "sport",
      "hiking",
      "horse-riding",
      "birdwatching",
      "glacier tours",
    ],
    "loc-code": "cl-c",
    address:
      "KM 5 Norte, Puerto Bories, Puerto Natales, Natales, Magallanes y la Antártica Chilena, Chile",
    location: {
      latitude: -51.7206,
      longitude: -72.5068,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa", "pool"],
    web: "https://www.thesingular.com/patagonia/",
    images: [],
  },
  {
    id: 39,
    name: "Explora Rapa Nui",
    activities: [
      "outdoors",
      "sport",
      "hiking",
      "horse-riding",
      "cycling",
      "stargazing",
    ],
    "loc-code": "cl-c",
    address: "Unnamed Road, Isla de Pascua, Valparaíso Region, Chile",
    location: {
      latitude: -27.1384,
      longitude: -109.4275,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["restaurant", "spa", "pool"],
    web: "https://www.explora.com/hotels-and-travesias/easter-island/explora-rapa-nui/",
    images: [],
  },
  {
    id: 40,
    name: "Amangani",
    activities: [
      "sport",
      "mountaineering",
      "skiing",
      "mountain views",
      "outdoors",
    ],
    "loc-code": "us-c",
    address: "1535 NE Butte Road, Jackson, Wyoming 83001, USA",
    location: {
      latitude: 43.5285,
      longitude: -110.666,
    },
    rating: 4.7,
    price: "luxury",
    comfort: ["restaurant", "spa", "gym"],
    web: "https://www.aman.com/resorts/amangani",
    images: [],
  },
  {
    id: 41,
    name: "Southern Ocean Lodge",
    activities: ["wildlife exploration", "relax", "wine-tasting", "outdoors"],
    "loc-code": "au-c",
    address:
      "Hanson Bay Road, Kangaroo Island, South Australia 5222, Australia",
    location: {
      latitude: -36.0357,
      longitude: 137.2335,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["restaurant", "spa", "library"],
    web: "https://southernoceanlodge.com.au/",
    images: [],
  },
  {
    id: 42,
    name: "Explora Patagonia",
    activities: [
      "canyon exploration",
      "forest hikes",
      "lake excursions",
      "outdoors",
    ],
    "loc-code": "cl-c",
    address: "Hotel Salto Chico, Torres del Paine National Park, Chile",
    location: {
      latitude: -50.9423,
      longitude: -73.4068,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa", "bar"],
    web: "https://www.explora.com/patagonia/",
    images: [],
  },
  {
    id: 43,
    name: "The Brando",
    activities: [
      "snorkeling",
      "kayaking",
      "paddleboarding",
      "outdoors",
      "sport",
    ],
    "loc-code": "pf-c",
    address: "Tetiaroa Private Island, Arue, French Polynesia",
    location: {
      latitude: -17.5695,
      longitude: -149.6079,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["restaurant", "spa", "beach"],
    web: "https://thebrando.com/",
    images: [],
  },
  {
    id: 44,
    name: "Ladera Resort",
    activities: ["ziplining", "hiking", "sulphur springs visit", "outdoors"],
    "loc-code": "lc-c",
    address: "Soufrière, St Lucia",
    location: {
      latitude: 13.8569,
      longitude: -61.0565,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa", "pool"],
    web: "https://www.ladera.com/",
    images: [],
  },
  {
    id: 45,
    name: "The Datai Langkawi",
    activities: [
      "rainforest walks",
      "guided nature tours",
      "beach yoga",
      "outdoors",
      "relax",
      "golf",
    ],
    "loc-code": "my-c",
    address: "Jalan Teluk Datai, 07000 Langkawi, Kedah, Malaysia",
    location: {
      latitude: 6.4254,
      longitude: 99.7089,
    },
    rating: 4.8,
    price: "luxury",
    comfort: ["restaurant", "spa"],
    web: "https://www.thedatai.com/langkawi/",
    images: [],
  },
  {
    id: 46,
    name: "Amanwana",
    activities: [
      "outdoors",
      "jungle trekking",
      "diving",
      "snorkeling",
      "sport",
    ],
    "loc-code": "id-c",
    address: "Moyo Island, Sumbawa, West Nusa Tenggara, Indonesia",
    location: {
      latitude: -8.3028,
      longitude: 117.3863,
    },
    rating: 4.7,
    price: "luxury",
    comfort: ["restaurant", "spa", "beach"],
    web: "https://www.aman.com/resorts/amanwana",
    images: [],
  },
  {
    id: 47,
    name: "Singita Lebombo Lodge",
    activities: [
      "safari",
      "hiking",
      "outdoors",
      "relax",
    ],
    "loc-code": "za-c",
    address: "N'wanetsi Concession, Kruger National Park, South Africa",
    location: {
      latitude: -24.3083,
      longitude: 31.7053,
    },
    rating: 4.9,
    price: "luxury",
    comfort: ["restaurant", "spa", "pool"],
    web: "https://singita.com/lebombo-lodge/",
    images: [],
  },
  {
    id: 48,
    name: "Hotel France",
    activities: [
      "outdoors",
      "sport",
      "art",
      "cycling",
      "music",
    ],
    address: "Soborna Street, Vinnytsia, Ukraine",
    "loc-code": "ua-с",
    location: {
      latitude: 49.2331,
      longitude: 28.4682,
    },
    rating: 4.5,
    price: "budget",
    comfort: ["restaurant", "parking", "wifi", "bar"],
    web: "http://www.hotelfrance.com",
    images: [],
  },
  {
    id: 49,
    name: "Safari-Club",
    activities: ["pool", "sport", "horse-riding"],
    address: "1A, Tsentralna Street, Vinnytsia, Ukraine",
    "loc-code": "ua-с",
    location: {
      latitude: 49.2475,
      longitude: 28.4953,
    },
    rating: 4.2,
    price: "midrange",
    comfort: ["wifi", "parking", "spa", "restaurant", "gym"],
    web: "http://www.safari-club.com",
    images: [],
  },
  {
    id: 50,
    name: "Fenix Town",
    activities: ["relax", "spa", "sport", "bowling", "billiard"],
    address: "Khlebnaya Street 15, Vinnytsia, Ukraine",
    "loc-code": "ua-c",
    location: {
      latitude: 49.2345,
      longitude: 28.463,
    },
    rating: 4.3,
    price: "budget",
    comfort: ["wifi", "parking", "gym", "restaurant"],
    web: "http://www.fenixtown.com",
    images: [],
  },
  {
    id: 51,
    name: "Fairmont Grand Hotel Kyiv",
    activities: ["relax"],
    address: "Naberezhno-Khreshchatytska Street 1, Kyiv, Ukraine",
    "loc-code": "ua-c",
    location: {
      latitude: 50.4606,
      longitude: 30.5302,
    },
    rating: 5,
    price: "luxury",
    comfort: ["wifi", "parking", "spa", "restaurant", "bar"],
    web: "https://www.fairmont.com/kyiv/",
    images: [],
  },
  {
    id: 52,
    name: "Lisotel",
    activities: [
      "relax",
      "art",
      "outdoors",
      "kids",
      "painting",
      "crafts",
      "cycling",
    ],
    address: "Pishchane Tract 7, Rokytne 09600 Ukraine",
    "loc-code": "ua-c",
    location: {
      latitude: 49.6808,
      longitude: 30.4188,
    },
    rating: 5,
    price: "luxury",
    comfort: [
      "wifi",
      "parking",
      "pool",
      "restaurant",
      "pets",
      "lake",
      "fireplace",
    ],
    web: "https://lisotel.com.ua/en/",
    images: [
      "/assets/Lisotel/motanka.png",
      "/assets/Lisotel/restaurant.png",
      "/assets/Lisotel/makoviy.png",
      "/assets/Lisotel/lake.png",
      "/assets/Lisotel/baking.png",
      "/assets/Lisotel/horse.png",
      "/assets/Lisotel/painting.png",
    ],
  },
  {
    id: 53,
    name: "Opera Hotel",
    activities: ["relax", "spa", "wine-tasting"],
    address: "B. Khmelnitskogo St., 53, Kyiv, Ukraine",
    "loc-code": "ua-c",
    location: {
      latitude: 50.45,
      longitude: 30.5,
    },
    rating: 5,
    price: "luxury",
    description:
      "Opera Hotel combines luxury and cultural charm, offering unique themed suites and comprehensive spa services. The hotel's award-winning wine list is a highlight for connoisseurs.",
    comfort: ["wifi", "parking", "spa", "restaurant"],
    web: "https://opera-hotel.com/",
    images: [],
  },
  {
    id: 54,
    name: "Hotel Flamingo",
    activities: ["outdoors", "sport", "kids", "tennis", "beach", "relax"],
    "loc-code": "es-c",
    address: "Avinguda de Grècia, 5, 17258 L'Estartit, Girona, Spain",
    location: {
      latitude: 42.0503,
      longitude: 3.1977,
    },
    rating: 4,
    price: "midrange",
    description:
      "Hotel Flamingo offers comfortable accommodation and tennis facilities in a beautiful coastal setting. Guests can enjoy a range of activities including tennis, swimming in the outdoor pool, and exploring the nearby beaches.",
    comfort: ["wifi", "parking", "pool", "restaurant", "beach"],
    web: "https://www.hotelpanoramaestartit.com/",
    images: [],
  },
  {
    id: 55,
    name: "Novotel Phuket Resort",
    activities: ["outdoors", "sport", "tennis", "relax", "beach"],
    "loc-code": "th-c",
    address:
      "Patong Beach, 282 Phrabaramee Rd, Pa Tong, Kathu District, Phuket 83150, Thailand",
    location: {
      latitude: 7.9079,
      longitude: 98.2973,
    },
    rating: 4,
    price: "midrange",
    description:
      "Overlooking Patong Beach, this hotel offers tennis courts, a fitness center, and three tiered swimming pools. It’s a great option for those wanting to enjoy both tennis and the vibrant life of Phuket.",
    comfort: [
      "wifi",
      "parking",
      "pool",
      "restaurant",
      "gym",
      "beach",
    ],
    web: "https://all.accor.com/hotel/1965/index.en.shtml",
    images: [],
  },
  {
    id: 56,
    name: "Hotel Panorama",
    activities: ["outdoors", "sport", "tennis", "spa", "relax"],
    "loc-code": "cs-c",
    address: "V Lomech 11, 323 00 Plzeň 1, Czech Republic",
    location: {
      latitude: 49.75,
      longitude: 13.3775,
    },
    rating: 3,
    price: "midrange",
    description:
      "Situated in the city of Plzeň, Hotel Panorama provides tennis facilities along with a wellness center and comfortable rooms. The hotel is also close to the city center, making it convenient for exploring local attractions.",
    comfort: ["wifi", "parking", "restaurant"],
    web: "http://www.panorama-pm.cz/",
    images: [],
  },
  {
    "id": 57,
    "name": "Hôtel de Paris Monte-Carlo",
    "activities": [
      "outdoors",
      "sport",
      "spa",
      "relax",
      "casino",
      "gourmet-dining",
    ],
    "loc-code": "mc-c",
    "address": "Place du Casino, 98000 Monaco",
    "location": {
      "latitude": 43.7384,
      "longitude": 7.4286
    },
    "rating": 5,
    "price": "luxury",
    "description": "The Hôtel de Paris Monte-Carlo is an iconic luxury hotel located in the heart of Monaco. The hotel features an on-premises casino, a world-class spa, exquisite dining options, and luxury shopping. It is renowned for its elegance and sophistication, offering guests a truly memorable stay.",
    "comfort": ["wifi", "valet-parking", "pool", "restaurant", "spa", "fitness-center"],
    "web": "https://www.montecarlosbm.com/en/hotel-monaco/hotel-paris-monte-carlo",
    images: [],
  }
  
];

export default hotels;
